src/Entity/Property.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;





/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @Vich\Uploadable()
 * @UniqueEntity("title")
 */
class Property
{
    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;
    /**************************************vich upload ***************************/

     /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;
    
    /**
     * @Assert\Image(mimeTypes="image/jpeg")
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     * @var File
     */
    private $imageFile;


    /**
     * @ORM\Column(type="datetime")
     *
     */
    private $updated_at;

    /**************************************vich upload ***************************/


    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $floor;

    /**
     * @ORM\Column(type="string")
     */
    private $heat;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="string")
     */
    private $price;

    /**
     * @ORM\Column(type="boolean", options={"defaul":false})
     */
    private $sold = 0;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="integer")
     */
    private $postalCode;

    /**
     * @ORM\Column(type="string")
     */
    private $parking;

    /**
     * @ORM\Column(type="integer")
     */
    private $bathrooms;

     /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="properties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Type", inversedBy="properties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comments", mappedBy="property")
     */
    private $comments;


    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->createdAt = new \DateTime();
    }
     
  
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
    //slugyfy title
    public function getSlug():string
    {
        $slugify = new Slugify();
        return $slugify->slugify($this->title); 
    }
    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /************************************FOR IMAGE ****************************/
    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File $imageFile
     * @return Property
     */
    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;

        if ($this->imageFile instanceof  UploadedFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setFilename(?string $filename): void
    {
        $this->filename = $filename;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /************************************FOR IMAGE ****************************/

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(?int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getHeat(): ?string
    {
        return $this->heat;
    }

    public function setHeat(string $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    // public function getHeatType():string
    // {
    //     return self::HEAT[$this->heat];
    // }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormatedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getSold(): ? bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?int
    {
        return $this->postalCode;
    }

    public function setPostalCode(int $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getParking(): ?string
    {
        return $this->parking;
    }

    public function setParking(string $parking): self
    {
        $this->parking = $parking;

        return $this;
    }

    public function getBathrooms(): ?int
    {
        return $this->bathrooms;
    }

    public function setBathrooms(int $bathrooms): self
    {
        $this->bathrooms = $bathrooms;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setProperty($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getProperty() === $this) {
                $comment->setProperty(null);
            }
        }

        return $this;
    }

  


 
  
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    // /**
    //  * @Route("/", name="home")
    //  */
    // public function index()
    // {
    //     return $this->render('home/index.html.twig');
    // }


    /**
     * @Route("/about", name="about")
     */
    public function about()
    {
        return $this->render('home/about.html.twig');
    }



    /**
    * @Route("/contact", name="contact")
    */
    public function contact()
    {
        return $this->render('home/contact.html.twig');
    }
}

templates/home/annonce-vendre.html.twig
{% extends "base.html.twig" %}
{% block title 'Annonces' %}

  {% block body %}
    {# include menu #}
    {% include "includes/menu.html.twig" %}


    <!--/ Intro Single star /-->
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">Biens à Vendre</h1>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--/ Intro Single End /-->

    <!--/ Property Grid Star /-->
    <section class="property-grid grid">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="grid-option">
              <form>
                <select class="custom-select">
                  <option selected>Tous</option>
                  <option value="1">Appartement</option>
                  <option value="2">Maison</option>

                </select>
              </form>
            </div>
          </div>

          {% for annonce in annonce_vendre %}
            <div class="col-md-4">
              <div class="card-box-a card-shadow">
                <div class="img-box-a">
                  <img alt="" class="img-a img-fluid" src="{{vich_uploader_asset(annonce, 'imageFile')}}">
                </div>
                <div class="card-overlay">
                  <div class="card-overlay-a-content">
                    <div class="card-header-a">
                      <h2 class="card-title-a">
                        <a href="#">{{annonce.title}}</a>
                      </h2>
                    </div>
                    <div class="card-body-a">
                      <div class="price-box d-flex">
                        <span class="price-a">€
                          {{annonce.formatedPrice}}</span>

                      </div>
                      <a class="link-a" href="{{path('property_show', {id:annonce.id, slug:annonce.slug})}}">Plus de Details
                        <i class="fa fa-angle-right"></i>
                      </a>
                    </div>
                    <div class="card-footer-a">
                      <ul class="card-info d-flex justify-content-around">
                        <li>
                          <h4 class="card-info-title">Surface</h4>
                          <span>{{ annonce.surface }}M²</span>
                        </li>
                        <li>
                          <h4 class="card-info-title">Pièces</h4>
                          <span>{{ annonce.rooms }}</span>
                        </li>
                        <li>
                          <h4 class="card-info-title">Chambres</h4>
                          <span>{{ annonce.rooms -1}}</span>
                        </li>
                        <li>
                          <h4 class="card-info-title">Etage</h4>
                          {% if annonce.floor == 0 %}
                            <span>Rez de Chaussé
                            </span>
                          {% else %}
                            <span>{{annonce.floor}}

                            </span>
                          {% endif %}
                        </li>
                      </ul>

                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}

        </div>
      </div>
    </section>
    <!--/ Property Grid End /-->


    {# include footer #}
    {% include "includes/footer.html.twig" %}

  {% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}

  {# include menu #}
  {% include "includes/menu.html.twig" %}

  {# include menu #}
  {% include "includes/header.html.twig" %}

  {# Property Rent Starts #}
  <section class="section-property section-t8">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="title-wrap d-flex justify-content-between">
            <div class="title-box">
              <h2 class="title-a">Louer</h2>
            </div>
            <div class="title-link">
              <a href="{{path('annonce_louer')}}">Voir Tous

                <i class="fa fa-angle-right"></i>

              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="owl-carousel owl-theme property-carousel">
        {% for property_louer in properties_louer | slice(0,6) %}
          <div class="carousel-item-b">
            <div class="card-box-a card-shadow">
              <div class="img-box-a">
                <img alt="" class="img-a img-fluid" src="{{vich_uploader_asset(property_louer, 'imageFile')}}">

              </div>
              <div class="card-overlay">
                <div class="card-overlay-a-content">
                  <div class="card-header-a">
                    <h2 class="card-title-a">
                      <a href="{{path('property_show', {id:property_louer.id, slug: property_louer.slug})}}">{{property_louer.title}}</a>

                    </h2>
                  </div>
                  <div class="card-body-a">
                    <div class="price-box d-flex">
                      <span class="price-a">€
                        {{property_louer.price}}
                        / mois</span>
                    </div>
                    <a class="link-a" href="{{path('property_show', {id:property_louer.id, slug: property_louer.slug})}}">Plus de details
                      <i class="fa fa-angle-right"></i>
                    </a>
                  </div>
                  <div class="card-footer-a">
                    <ul class="card-info d-flex justify-content-around">
                      <li>
                        <h4 class="card-info-title">Surface</h4>
                        <span>{{ property_louer.surface }}M²</span>
                      </li>
                      <li>
                        <h4 class="card-info-title">Pièces</h4>
                        <span>{{ property_louer.rooms }}</span>
                      </li>
                      <li>
                        <h4 class="card-info-title">Chambres</h4>
                        <span>{{ property_louer.rooms -1}}</span>
                      </li>
                      <li>
                        <h4 class="card-info-title">Etage</h4>
                        {% if property_louer.floor == 0 %}
                          <span>Rez de Chaussé
                          </span>
                        {% else %}
                          <span>{{property_louer.floor}}
                          </span>
                        {% endif %}
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}

      </div>
    </div>
  </section>
  {# Property Rent End #}

  {# Property Sales Start #}
  <section class="section-property section-t8">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="title-wrap d-flex justify-content-between">
            <div class="title-box">
              <h2 class="title-a">Vendre</h2>
            </div>
            <div class="title-link">
              <a href="{{path('annonce_vendre')}}">Voir Tous
                <i class="fa fa-angle-right"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="owl-carousel owl-theme property-carousel">
        {% for property_vendre in properties_vendre | slice(0,6) %}
          <div class="carousel-item-b">
            <div class="card-box-a card-shadow">
              <div class="img-box-a">
                <img alt="" class="img-a img-fluid" src="{{vich_uploader_asset(property_vendre, 'imageFile')}}">
              </div>
              <div class="card-overlay">
                <div class="card-overlay-a-content">
                  <div class="card-header-a">
                    <h2 class="card-title-a">
                      <a href="{{path('property_show', {id:property_vendre.id, slug: property_vendre.slug})}}">{{property_vendre.title}}</a>

                    </h2>
                  </div>
                  <div class="card-body-a">
                    <div class="price-box d-flex">
                      <span class="price-a">€
                        {{property_vendre.formatedPrice}}
                      </span>
                    </div>
                    <a class="link-a" href="{{path('property_show', {id:property_vendre.id, slug: property_vendre.slug})}}">Plus de details
                      <i class="fa fa-angle-right"></i>
                    </a>
                  </div>
                  <div class="card-footer-a">
                    <ul class="card-info d-flex justify-content-around">
                      <li>
                        <h4 class="card-info-title">Surface</h4>
                        <span>{{ property_vendre.surface }}M²</span>
                      </li>
                      <li>
                        <h4 class="card-info-title">Pièces</h4>
                        <span>{{ property_vendre.rooms }}</span>
                      </li>
                      <li>
                        <h4 class="card-info-title">Chambres</h4>
                        <span>{{ property_vendre.rooms -1}}</span>
                      </li>
                      <li>
                        <h4 class="card-info-title">Chauffage</h4>
                        <span>{{ property_vendre.heat}}</span>
                      </li>

                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}

      </div>
    </div>
  </section>


  {# Property Sales End #}


  {% include "includes/footer.html.twig" %}
{% endblock %}

templates/home/profil.html.twig
{% extends 'base.html.twig' %}
{% block body %}

{# include menu #}
{% include "include/menu.html.twig" %}

 {# include header #}
 {% include "include/header.html.twig" %}

<div class="container">
<section class="news-box top-margin">
  <div class="container">
    <div class="row">
      <div class="section-heading">
        <h2>Profil</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
        <ul>
            <li>Nom: {{app.user.lastname}}</li>
        </ul>
      </div>
    </div>
    </div>
</section>
   
          
</div>








{# include footer #}
{% include "include/footer.html.twig" %}

{% endblock %}

templates/home/show.html.twig
{% extends "base.html.twig" %}

{% block body %}
  {% include "includes/menu.html.twig" %}


  <section class="intro-single">
    <div class="container mt-4">
      <div class="row">
        {% for message in app.flashes('success') %}
          <div class="alert alert-success">
            {{message}}
          </div>
        {% endfor %}
        <div class="col-md-12 col-lg-8">
          <div class="title-single-box">
            <h1 class="title-single">{{property.title}}</h1>
            <span class="color-text-a">{{property.city}},
              {{property.postalCode}}</span>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="property-single nav-arrow-b">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="owl-carousel owl-arrow gallery-property" id="property-single-carousel">
            <div class="carousel-item-b">
              <img alt="" src="{{vich_uploader_asset(property, 'imageFile')}}">
            </div>
            <div class="carousel-item-b">
              <img alt="" src="../assets/img/slide-3.jpg">
            </div>
            <div class="carousel-item-b">
              <img alt="" src="../assets/img/slide-1.jpg">
            </div>
          </div>
        </div>
      </div>{# row #}
    </div>{# container #}


    <div class="container">
      <div class="row">
        <div class="col-md-5 col-lg-4">
          <div class="property-price d-flex justify-content-center foo">
            <div class="card-header-c d-flex">
              <div class="card-box-ico">
                <span class="ion-money">€</span>
              </div>
              <div class="card-title-c align-self-center">
                <h5 class="title-c">{{property.formatedPrice}}</h5>
              </div>
            </div>
          </div>
          <div class="property-summary">
            <div class="title-box-d section-t4">
              <h3 class="title-d">Carectéristiques</h3>
            </div>
          </div>
          <div class="summary-list">
            <ul class="list">
              <li class="d-flex justify-content-between">
                <strong>Property ID:</strong>
                <span>1134</span>
              </li>
              <li class="d-flex justify-content-between">
                <strong>Location:</strong>
                <span>{{property.city}}, {{property.postalCode}}</span>
              </li>
              <li class="d-flex justify-content-between">
                <strong>Property Type:</strong>
                <span>House</span>
              </li>
              <li class="d-flex justify-content-between">
                <strong>Status:</strong>
                <span>Sale</span>
              </li>
              <li class="d-flex justify-content-between">
                <strong>Surface:</strong>
                <span>{{property.surface}}M
                  <sup>2</sup>
                </span>
              </li>
              <li class="d-flex justify-content-between">
                <strong>Pièces:</strong>
                <span>{{property.rooms}}</span>
              </li>
              <li class="d-flex justify-content-between">
                <strong>Chambres:</strong>
                <span>{{property.rooms -1}}</span>
              </li>
              <li class="d-flex justify-content-between">
                <strong>Salle de Bain:</strong>
                <span>{{ property.bathrooms }}</span>
              </li>
              <li class="d-flex justify-content-between">
                <strong>Chaffage:</strong>
                <span>{{property.heat}}</span>
              </li>
              <li class="d-flex justify-content-between">
                <strong>Parking:</strong>
                <span>{{property.parking}}</span>
              </li>
              <li class="d-flex justify-content-between">
                <strong>Etage:</strong>
                {% if property.floor == 0 %}
                  <span>Rez de Chaussé</span>
                {% else %}
                  <span>{{property.floor}}</span>
                {% endif %}
              </li>
            </ul>
          </div>
        </div>{# col-md-5 col-lg-4 #}

        <div class="col-md-7 col-lg-8">
          <div class="title-box-d">
            <h3 class="title-d">Description</h3>
          </div>
          <div class="property-description">
            <p class="description color-text-a">{{property.description}}</p>
          </div>
        </div>{# col-md-7 col-lg-8 #}
      </div>{# row #}
    </div>{# container #}



    <div class="container"> 
      <div class="row">
        <div class="col-md-10 offset-md-1">
          <ul class="nav nav-pills-a nav-pills mb-3 section-t3" id="pills-tab" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" id="pills-video-tab" data-toggle="pill" href="#pills-video" role="tab"
                aria-controls="pills-video" aria-selected="true">Video</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="pills-plans-tab" data-toggle="pill" href="#pills-plans" role="tab" aria-controls="pills-plans"
                aria-selected="false">Floor Plans</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="pills-map-tab" data-toggle="pill" href="#pills-map" role="tab" aria-controls="pills-map"
                aria-selected="false">Ubication</a>
            </li>
          </ul>
          <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="pills-video" role="tabpanel" aria-labelledby="pills-video-tab">
              <iframe src="https://player.vimeo.com/video/73221098" width="100%" height="460" frameborder="0"
                webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            </div>
            <div class="tab-pane fade" id="pills-plans" role="tabpanel" aria-labelledby="pills-plans-tab">
              <img src="../assets/img/plan2.jpg" alt="" class="img-fluid">
            </div>
            <div class="tab-pane fade" id="pills-map" role="tabpanel" aria-labelledby="pills-map-tab">
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3022.1422937950147!2d-73.98731968482413!3d40.75889497932681!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25855c6480299%3A0x55194ec5a1ae072e!2sTimes+Square!5e0!3m2!1ses-419!2sve!4v1510329142834"
                width="100%" height="460" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
          </div>
        </div>
      </div>
    </div>



    <div class="container">
      <div class="row section-t3">
        <div class="col-md-12">
          <div class="title-box-d">
            <h3 class="title-d">Contact Agent</h3>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 col-lg-4">
          <img src="../assets/img/agent-4.jpg" alt="" class="img-fluid">
        </div>
        <div class="col-md-6 col-lg-4">
          <div class="property-agent">
          <h4 class="title-agent">Anabella Geller</h4>
          <p class="color-text-a">Nulla porttitor accumsan tincidunt. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet
            dui. Quisque velit nisi, pretium ut lacinia in, elementum id enim.
          </p>
          <ul class="list-unstyled">
            <li class="d-flex justify-content-between">
              <strong>Phone:</strong>
              <span class="color-text-a">(222) 4568932</span>
            </li>
            <li class="d-flex justify-content-between">
              <strong>Mobile:</strong>
              <span class="color-text-a">777 287 378 737</span>
            </li>
            <li class="d-flex justify-content-between">
              <strong>Email:</strong>
              <span class="color-text-a">annabella@example.com</span>
            </li>
            <li class="d-flex justify-content-between">
              <strong>Skype:</strong>
              <span class="color-text-a">Annabela.ge</span>
            </li>
          </ul>
            <div class="socials-a">
              <ul class="list-inline">
                <li class="list-inline-item">
                  <a href="#">
                    <i class="fa fa-facebook" aria-hidden="true"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="#">
                    <i class="fa fa-twitter" aria-hidden="true"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="#">
                    <i class="fa fa-instagram" aria-hidden="true"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="#">
                    <i class="fa fa-pinterest-p" aria-hidden="true"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="#">
                    <i class="fa fa-dribbble" aria-hidden="true"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-4">
          <div class="property-contact">
           {{form_start(form)}}
              <div class="row">
                <div class="col-md-12 mb-1">
                  <div class="form-group">
                    {{form_row(form.firstname)}}
                  </div>
                </div>
                <div class="col-md-12 mb-1">
                  <div class="form-group">
                   {{form_row(form.lastname)}}
                  </div>
                </div>
                <div class="col-md-12 mb-1">
                  <div class="form-group">
                   {{form_row(form.phone)}}
                  </div>
                </div>
                <div class="col-md-12 mb-1">
                  <div class="form-group">
                   {{form_row(form.email)}}
                  </div>
                </div>
                <div class="col-md-12 mb-1">
                  <div class="form-group">
                    {{form_rest(form)}}
                  </div>
                </div>
                <div class="col-md-12">
                  <button type="submit" class="btn btn-a">Send Message</button>
                </div>
              </div>
            {{form_end(form)}}
          </div>
        </div>
      </div>
    </div>{# container #}
  </section>

{% include "includes/footer.html.twig" %}
{% endblock %}